const config = {
	signs: [
		{
			id: '101_gefahrstelle',
			filename: '101_gefahrstelle.svg',
			name: { de: 'Gefahrstelle' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '101-11_fussgaengerueberweg-rechts',
			filename: '101-11_fussgaengerueberweg-rechts.svg',
			name: { de: 'Fußgängerüberweg – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right', 'pedestrian'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '101-15_steinschlag-rechts',
			filename: '101-15_steinschlag-rechts.svg',
			name: { de: 'Steinschlag – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-21_fussgaengerueberweg-links',
			filename: '101-21_fussgaengerueberweg-links.svg',
			name: { de: 'Fußgängerüberweg – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left', 'pedestrian'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '101-25_steinschlag-links',
			filename: '101-25_steinschlag-links.svg',
			name: { de: 'Steinschlag – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-51_schnee-oder-eisglaette',
			filename: '101-51_schnee-oder-eisglaette.svg',
			name: { de: 'Schnee- oder Eisglätte' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-52_splitt-schotter',
			filename: '101-52_splitt-schotter.svg',
			name: { de: 'Splitt, Schotter' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-54_unzureichendes-lichtraumprofil',
			filename: '101-54_unzureichendes-lichtraumprofil.svg',
			name: { de: 'Unzureichendes Lichtraumprofil' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '105-10_doppelkurve-links-rechts',
			filename: '105-10_doppelkurve-links-rechts.svg',
			name: { de: 'Doppelkurve – zunächst links' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '105-20_doppelkurve-rechts-links',
			filename: '105-20_doppelkurve-rechts-links.svg',
			name: { de: 'Doppelkurve – zunächst rechts' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '112_unebene-fahrbahn',
			filename: '112_unebene-fahrbahn.svg',
			name: { de: 'Unebene Fahrbahn' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '114_schleuder-rutschgefahr',
			filename: '114_schleuder-rutschgefahr.svg',
			name: { de: 'Schleuder- oder Rutschgefahr' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '120_verengte-fahrbahn',
			filename: '120_verengte-fahrbahn.svg',
			name: { de: 'Verengte Fahrbahn' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '123_arbeitsstelle',
			filename: '123_arbeitsstelle.svg',
			name: { de: 'Arbeitsstelle' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '124_stau',
			filename: '124_stau.svg',
			name: { de: 'Stau' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '125_gegenverkehr',
			filename: '125_gegenverkehr.svg',
			name: { de: 'Gegenverkehr' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '131_lichtzeichenanlage',
			filename: '131_lichtzeichenanlage.svg',
			name: { de: 'Lichtzeichen­anla­ge' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '133-10_fussgaenger-rechts',
			filename: '133-10_fussgaenger-rechts.svg',
			name: { de: 'Fußgänger – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '133-20_fussgaenger-links',
			filename: '133-20_fussgaenger-links.svg',
			name: { de: 'Fußgänger – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '136-10_kinder-rechts',
			filename: '136-10_kinder-rechts.svg',
			name: { de: 'Kinder – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '136-20_kinder-links',
			filename: '136-20_kinder-links.svg',
			name: { de: 'Kinder – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '138-10_radverkehr-rechts',
			filename: '138-10_radverkehr-rechts.svg',
			name: { de: 'Radverkehr – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '138-20_radverkehr-links',
			filename: '138-20_radverkehr-links.svg',
			name: { de: 'Radverkehr – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '142-10_wildwechsel-rechts',
			filename: '142-10_wildwechsel-rechts.svg',
			name: { de: 'Wildwechsel – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '142-20_wildwechsel-links',
			filename: '142-20_wildwechsel-links.svg',
			name: { de: 'Wildwechsel – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '151_bahnuebergang',
			filename: '151_bahnuebergang.svg',
			name: { de: 'Bahnübergang' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '205_vorfahrt-gewaehren',
			filename: '205_vorfahrt-gewaehren.svg',
			name: { de: 'Vorfahrt gewähren' },
			tags: ['triangle', 'red'],
			frequency: 'high',
			location: ['city', 'highway'],
		},
		{
			id: '206_halt',
			filename: '206_halt.svg',
			name: { de: 'Halt. Vorfahrt gewährenVorfahrt gewähren' },
			tags: ['octogon', 'red'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '208_gegenverkehr-vorrang',
			filename: '208_gegenverkehr-vorrang.svg',
			name: { de: 'Vorrang des Gegenverkehrs' },
			tags: ['circle', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '209_fahrtrichtung-rechts',
			filename: '209_fahrtrichtung-rechts.svg',
			name: { de: 'Vorgeschriebene Fahrtrichtung – rechts' },
			tags: ['circle', 'blue', 'right'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '209-10_fahrtrichtung-links',
			filename: '209-10_fahrtrichtung-links.svg',
			name: { de: 'Vorgeschriebene Fahrtrichtung – links' },
			tags: ['circle', 'blue', 'left'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '209-30_fahrtrichtung-geradeaus',
			filename: '209-30_fahrtrichtung-geradeaus.svg',
			name: { de: 'Vorgeschriebene Fahrtrichtung – geradeaus' },
			tags: ['circle', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '211-10_fahrtrichtung-hier-links',
			filename: '211-10_fahrtrichtung-hier-links.svg',
			name: { de: 'Vorgeschriebene Fahrtrichtung — hier links' },
			tags: ['circle', 'blue', 'left'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '211_fahrtrichtung-hier-rechts',
			filename: '211_fahrtrichtung-hier-rechts.svg',
			name: { de: 'Vorgeschriebene Fahrtrichtung — hier rechts' },
			tags: ['circle', 'blue', 'right'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '215_kreisverkehr',
			filename: '215_kreisverkehr.svg',
			name: { de: 'Kreisverkehr' },
			tags: ['circle', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '220-10_einbahnstrasse-links',
			filename: '220-10_einbahnstrasse-links.svg',
			name: { de: 'Einbahnstraße – linksweisend' },
			tags: ['rechtangle', 'blue', 'left'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '220-20_einbahnstrasse-rechts',
			filename: '220-20_einbahnstrasse-rechts.svg',
			name: { de: 'Einbahnstraße – rechtlinksweisend' },
			tags: ['rechtangle', 'blue', 'right'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '222-10_vorbeifahrt-links',
			filename: '222-10_vorbeifahrt-links.svg',
			name: { de: 'Vorgeschriebene Vorbeifahrt – links vorbei' },
			tags: ['circle', 'blue', 'left'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '222_vorbeifahrt-rechts',
			filename: '222_vorbeifahrt-rechts.svg',
			name: { de: 'Vorgeschriebene Vorbeifahrt – rechts vorbei' },
			tags: ['circle', 'blue', 'right'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '224_haltestelle',
			filename: '224_haltestelle.svg',
			name: { de: 'Haltestelle' },
			tags: ['circle', 'green', 'yellow'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '229_taxenstand',
			filename: '229_taxenstand.svg',
			name: { de: 'Taxenstand' },
			tags: ['rectangle', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '237_sonderweg-radfahrer',
			filename: '237_sonderweg-radfahrer.svg',
			name: { de: 'Radweg' },
			tags: ['circle', 'blue'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '239_gehweg',
			filename: '239_gehweg.svg',
			name: { de: 'Gehweg' },
			tags: ['circle', 'blue'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '242.1_fussgaengerzone-beginn',
			filename: '242.1_fussgaengerzone-beginn.svg',
			name: { de: 'Beginn einer Fußgängerzone' },
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '242.2_fussgaengerzone-ende',
			filename: '242.2_fussgaengerzone-ende.svg',
			name: { de: 'Ende einer Fußgängerzone' },
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '244.3_fahrradzone-beginn',
			filename: '244.3_fahrradzone-beginn.svg',
			name: { de: 'Beginn einer Fahrradstraße' },
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '244.4_fahrradzone-ende',
			filename: '244.4_fahrradzone-ende.svg',
			name: { de: 'Ende einer Fahrradstraße' },
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '245_bussonderfahrstreifen',
			filename: '245_bussonderfahrstreifen.svg',
			name: { de: 'Bussonder­fahr­streifen' },
			tags: ['circle', 'blue'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '250_fahrzeuge-verbot',
			filename: '250_fahrzeuge-verbot.svg',
			name: { de: 'Verbot für Fahrzeuge aller Art' },
			tags: ['circle', 'red'],
			frequency: 'high',
			location: ['city', 'highway'],
		},
		{
			id: '267_einfahrt-verbot',
			filename: '267_einfahrt-verbot.svg',
			name: { de: 'Verbot der Einfahrt' },
			tags: ['circle', 'red'],
			frequency: 'high',
			location: ['city', 'highway'],
		},
		{
			id: '270.1_umweltzone-beginn',
			filename: '270.1_umweltzone-beginn.svg',
			name: {
				de: 'Beginn eines Verkehrs­verbots zur Vermin­derung schädlicher Luftverunreinigungen in einer Zone',
			},
			tags: ['square', 'white'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '270.2_umweltzone-ende',
			filename: '270.2_umweltzone-ende.svg',
			name: {
				de: 'Ende eines Verkehrs­verbots zur Vermin­derung schädlicher Luftverunreinigungen in einer Zone',
			},
			tags: ['square', 'white'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '272_wendens-verbot',
			filename: '272_wendens-verbot.svg',
			name: { de: 'Verbot des Wendens' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '274-100_hoechstgeschwindigkeit-100',
			filename: '274-100_hoechstgeschwindigkeit-100.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 100' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '274-110_hoechstgeschwindigkeit-110',
			filename: '274-110_hoechstgeschwindigkeit-110.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 110' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['highway'],
		},
		{
			id: '274-120_hoechstgeschwindigkeit-120',
			filename: '274-120_hoechstgeschwindigkeit-120.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 120' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['highway'],
		},
		{
			id: '274-130_hoechstgeschwindigkeit-130',
			filename: '274-130_hoechstgeschwindigkeit-130.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 130' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['highway'],
		},
		{
			id: '274-30_hoechstgeschwindigkeit-30',
			filename: '274-30_hoechstgeschwindigkeit-30.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 30' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '274-40_hoechstgeschwindigkeit-40',
			filename: '274-40_hoechstgeschwindigkeit-40.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 40' },
			tags: ['circle', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '274-50_hoechstgeschwindigkeit-50',
			filename: '274-50_hoechstgeschwindigkeit-50.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 50' },
			tags: ['circle', 'red'],
			frequency: 'high',
			location: ['city', 'highway'],
		},
		{
			id: '274-60_hoechstgeschwindigkeit-60',
			filename: '274-60_hoechstgeschwindigkeit-60.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 60' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '274-70_hoechstgeschwindigkeit-70',
			filename: '274-70_hoechstgeschwindigkeit-70.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 70' },
			tags: ['circle', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '274-80_hoechstgeschwindigkeit-80',
			filename: '274-80_hoechstgeschwindigkeit-80.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 80' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '274-90_hoechstgeschwindigkeit-90',
			filename: '274-90_hoechstgeschwindigkeit-90.svg',
			name: { de: 'Zulässige Höchst­geschwindigkeit: 90' },
			tags: ['circle', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '274.1_zone-30-beginn',
			filename: '274.1_zone-30-beginn.svg',
			name: { de: 'Beginn einer Tempo 30-Zone' },
			tags: ['square', 'white'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '274.2_zone-30-ende',
			filename: '274.2_zone-30-ende.svg',
			name: { de: 'Ende einer Tempo 30-Zone' },
			tags: ['square', 'white'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '276_ueberholverbot-kraftfahrzeuge',
			filename: '276_ueberholverbot-kraftfahrzeuge.svg',
			name: { de: 'Überholverbot für Kraftfahrzeuge aller Art' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '277_ueberholverbot-kraftfahrzeuge-schwer',
			filename: '277_ueberholverbot-kraftfahrzeuge-schwer.svg',
			name: { de: 'Überholverbot für Kraftfahrzeuge über 3,5 t' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '280_ueberholverbot-kraftfahrzeuge-ende',
			filename: '280_ueberholverbot-kraftfahrzeuge-ende.svg',
			name: {
				de: 'Ende des Überholverbotes für Kraftfahrzeuge aller Art',
			},
			tags: ['circle', 'white'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '281_ueberholverbot-kraftfahrzeuge-schwer-ende',
			filename: '281_ueberholverbot-kraftfahrzeuge-schwer-ende.svg',
			name: {
				de: 'Ende des Überholverbotes für Kraftfahrzeuge über 3,5 t',
			},
			tags: ['circle', 'white'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '282_ende-saemtlicher-verbote',
			filename: '282_ende-saemtlicher-verbote.svg',
			name: {
				de: 'Ende sämtlicher streckenbezogen­er Geschwindigkeits­beschränkungen und Überholverbote',
			},
			tags: ['circle', 'white'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '283_haltverbot-absolutes',
			filename: '283_haltverbot-absolutes.svg',
			name: { de: 'Absolutes Haltverbot' },
			tags: ['circle', 'red'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '290.1_zone-halteverbot-beginn',
			filename: '290.1_zone-halteverbot-beginn.svg',
			name: {
				de: 'Beginn eines eingeschränkten Haltverbotes für eine Zone',
			},
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '290.2_zone-halteverbot-ende',
			filename: '290.2_zone-halteverbot-ende.svg',
			name: {
				de: 'Ende eines eingeschränkten Haltverbotes für eine Zone',
			},
			tags: ['square', 'white'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '306_vorfahrtstrasse',
			filename: '306_vorfahrtstrasse.svg',
			name: { de: 'Vorfahrtstraße' },
			tags: ['diamond', 'white', 'yellow'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '308_vorrang-vor-dem-gegenverkehr',
			filename: '308_vorrang-vor-dem-gegenverkehr.svg',
			name: { de: 'Vorrang vor dem Gegenverkehr' },
			tags: ['square', 'blue'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '314_parken',
			filename: '314_parken.svg',
			name: { de: 'Parken' },
			tags: ['square', 'blue'],
			frequency: 'high',
			location: ['city', 'highway'],
		},
		{
			id: '314-50_parkhaus-parkgarage',
			filename: '314-50_parkhaus-parkgarage.svg',
			name: { de: 'Parkhaus, Parkgarage' },
			tags: ['square', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '314.1_zone-parkraum-beginn',
			filename: '314.1_zone-parkraum-beginn.svg',
			name: { de: 'Beginn einer Parkraum­bewirtschaftungszone' },
			tags: ['square', 'white', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '314.2_zone-parkraum-ende',
			filename: '314.2_zone-parkraum-ende.svg',
			name: { de: 'Ende einer Parkraum­bewirtschaftungszone' },
			tags: ['square', 'white', 'blue'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '325.1_verkehrsberuhigtes-bereich-beginn',
			filename: '325.1_verkehrsberuhigtes-bereich-beginn.svg',
			name: { de: 'Beginn eines verkehrsberuhigten Bereichs' },
			tags: ['rectangle', 'blue'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '325.2_verkehrsberuhigtes-bereichs-ende',
			filename: '325.2_verkehrsberuhigtes-bereichs-ende.svg',
			name: { de: 'Ende eines verkehrsberuhigten Bereichs' },
			tags: ['rectangle', 'blue'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '327_tunnel',
			filename: '327_tunnel.svg',
			name: { de: 'Tunnel' },
			tags: ['square', 'blue'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '330.1_autobahn',
			filename: '330.1_autobahn.svg',
			name: { de: 'Autobahn' },
			tags: ['square', 'blue'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '330.2_autobahn-ende',
			filename: '330.2_autobahn-ende.svg',
			name: { de: 'Ende der Autobahn' },
			tags: ['square', 'blue'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '331.1_kraftfahrstrasse-beginn',
			filename: '331.1_kraftfahrstrasse-beginn.svg',
			name: { de: 'Kraftfahrstraße' },
			tags: ['square', 'blue'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '331.2_kraftfahrstrasse-ende',
			filename: '331.2_kraftfahrstrasse-ende.svg',
			name: { de: 'Ende der Kraftfahrstraße' },
			tags: ['square', 'blue'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '333_ausfahrt-autobahn',
			filename: '333_ausfahrt-autobahn.svg',
			name: { de: 'Ausfahrt von der Autobahn' },
			tags: ['rectangle', 'blue', 'landscape'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '333.1_ausfahrt-nicht-autobahn',
			filename: '333.1_ausfahrt-nicht-autobahn.svg',
			name: { de: 'Ausfahrt von anderen Straßen außerhalb der Autobahn' },
			tags: ['rectangle', 'yellow', 'landscape'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '350-10_fussgaengerueberweg-rechts',
			filename: '350-10_fussgaengerueberweg-rechts.svg',
			name: { de: 'Fußgängerüberweg, Aufstellung rechts' },
			tags: ['square', 'blue', 'right', 'pedestrian'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '350-20_fussgaengerueberweg-links',
			filename: '350-20_fussgaengerueberweg-links.svg',
			name: { de: 'Fußgängerüberweg, Aufstellung links' },
			tags: ['square', 'blue', 'left', 'pedestrian'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '357_sackgasse',
			filename: '357_sackgasse.svg',
			name: { de: 'Sackgasse' },
			tags: ['square', 'blue'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '454-10_umleitung-links',
			filename: '454-10_umleitung-links.svg',
			name: { de: 'Umleitungs­wegweiser, linksweisend' },
			tags: ['rectangle', 'yellow', 'left'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '454-20_umleitung-rechts',
			filename: '454-20_umleitung-rechts.svg',
			name: { de: 'Umleitungs­wegweiser, rechtsweisend' },
			tags: ['rectangle', 'yellow', 'right'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '720_gruenpfeil',
			filename: '720_gruenpfeil.svg',
			name: { de: 'Grünpfeilschild' },
			tags: ['square', 'black'],
			frequency: 'low',
			location: ['city'],
		},
	],
};
export default config;
