const config = {
	signs: [
		{
			id: '101_gefahrstelle',
			filename: '101_gefahrstelle.svg',
			name: { de: 'Gefahrstelle' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'medium',
			location: ['city', 'highway'],
		},
		{
			id: '101-11_fussgaengerueberweg-rechts',
			filename: '101-11_fussgaengerueberweg-rechts.svg',
			name: { de: 'Fußgängerüberweg – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right', 'pedestrian'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '101-15_steinschlag-rechts',
			filename: '101-15_steinschlag-rechts.svg',
			name: { de: 'Steinschlag – Aufstellung rechts' },
			tags: ['triangle', 'danger', 'red', 'right'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-21_fussgaengerueberweg-links',
			filename: '101-21_fussgaengerueberweg-links.svg',
			name: { de: 'Fußgängerüberweg – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left', 'pedestrian'],
			frequency: 'medium',
			location: ['city'],
		},
		{
			id: '101-25_steinschlag-links',
			filename: '101-25_steinschlag-links.svg',
			name: { de: 'Steinschlag – Aufstellung links' },
			tags: ['triangle', 'danger', 'red', 'left'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-51_schnee-oder-eisglaette',
			filename: '101-51_schnee-oder-eisglaette.svg',
			name: { de: 'Schnee- oder Eisglätte' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-52_splitt-schotter',
			filename: '101-52_splitt-schotter.svg',
			name: { de: 'Splitt, Schotter' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '101-54_unzureichendes-lichtraumprofil',
			filename: '101-54_unzureichendes-lichtraumprofil.svg',
			name: { de: 'Unzureichendes Lichtraumprofil' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '105-10_doppelkurve-links-rechts',
			filename: '105-10_doppelkurve-links-rechts.svg',
			name: { de: 'Doppelkurve – zunächst links' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '105-20_doppelkurve-rechts-links',
			filename: '105-20_doppelkurve-rechts-links.svg',
			name: { de: 'Doppelkurve – zunächst rechts' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '112_unebene-fahrbahn',
			filename: '112_unebene-fahrbahn.svg',
			name: { de: 'Unebene Fahrbahn' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{
			id: '114_schleuder-rutschgefahr',
			filename: '114_schleuder-rutschgefahr.svg',
			name: { de: 'Schleuder- oder Rutschgefahr' },
			tags: ['triangle', 'danger', 'red'],
			frequency: 'low',
			location: ['city'],
		},
		{ id: '120_verengte-fahrbahn', filename: '120_verengte-fahrbahn.svg' },
		{ id: '123_arbeitsstelle', filename: '123_arbeitsstelle.svg' },
		{ id: '124_stau', filename: '124_stau.svg' },
		{ id: '125_gegenverkehr', filename: '125_gegenverkehr.svg' },
		{
			id: '131_lichtzeichenanlage',
			filename: '131_lichtzeichenanlage.svg',
		},
		{
			id: '133-10_fussgaenger-rechts',
			filename: '133-10_fussgaenger-rechts.svg',
		},
		{
			id: '133-20_fussgaenger-links',
			filename: '133-20_fussgaenger-links.svg',
		},
		{ id: '136-10_kinder-rechts', filename: '136-10_kinder-rechts.svg' },
		{ id: '136-20_kinder-links', filename: '136-20_kinder-links.svg' },
		{
			id: '138-10_radverkehr-rechts',
			filename: '138-10_radverkehr-rechts.svg',
		},
		{
			id: '138-20_radverkehr-links',
			filename: '138-20_radverkehr-links.svg',
		},
		{
			id: '142-10_wildwechsel-rechts',
			filename: '142-10_wildwechsel-rechts.svg',
		},
		{
			id: '142-20_wildwechsel-links',
			filename: '142-20_wildwechsel-links.svg',
		},
		{ id: '151_bahnuebergang', filename: '151_bahnuebergang.svg' },
		{
			id: '205_vorfahrt-gewaehren',
			filename: '205_vorfahrt-gewaehren.svg',
		},
		{ id: '206_halt', filename: '206_halt.svg' },
		{
			id: '208_gegenverkehr-vorrang',
			filename: '208_gegenverkehr-vorrang.svg',
		},
		{
			id: '209-10_fahrtrichtung-links',
			filename: '209-10_fahrtrichtung-links.svg',
		},
		{
			id: '209-30_fahrtrichtung-geradeaus',
			filename: '209-30_fahrtrichtung-geradeaus.svg',
		},
		{
			id: '209_fahrtrichtung-rechts',
			filename: '209_fahrtrichtung-rechts.svg',
		},
		{
			id: '211-10_fahrtrichtung-hier-links',
			filename: '211-10_fahrtrichtung-hier-links.svg',
		},
		{
			id: '211_fahrtrichtung-hier-rechts',
			filename: '211_fahrtrichtung-hier-rechts.svg',
		},
		{ id: '215_kreisverkehr', filename: '215_kreisverkehr.svg' },
		{
			id: '220-10_einbahnstrasse-links',
			filename: '220-10_einbahnstrasse-links.svg',
		},
		{
			id: '220-20_einbahnstrasse-rechts',
			filename: '220-20_einbahnstrasse-rechts.svg',
		},
		{
			id: '222-10_vorbeifahrt-links',
			filename: '222-10_vorbeifahrt-links.svg',
		},
		{
			id: '222_vorbeifahrt-rechts',
			filename: '222_vorbeifahrt-rechts.svg',
		},
		{ id: '224_haltestelle', filename: '224_haltestelle.svg' },
		{ id: '229_taxenstand', filename: '229_taxenstand.svg' },
		{
			id: '237_sonderweg-radfahrer',
			filename: '237_sonderweg-radfahrer.svg',
		},
		{ id: '239_gehweg', filename: '239_gehweg.svg' },
		{
			id: '242.1_fussgaengerzone-beginn',
			filename: '242.1_fussgaengerzone-beginn.svg',
		},
		{
			id: '242.2_fussgaengerzone-ende',
			filename: '242.2_fussgaengerzone-ende.svg',
		},
		{
			id: '244.3_fahrradzone-beginn',
			filename: '244.3_fahrradzone-beginn.svg',
		},
		{
			id: '244.4_fahrradzone-ende',
			filename: '244.4_fahrradzone-ende.svg',
		},
		{
			id: '245_bussonderfahrstreifen',
			filename: '245_bussonderfahrstreifen.svg',
		},
		{ id: '250_fahrzeuge-verbot', filename: '250_fahrzeuge-verbot.svg' },
		{
			id: '257_sackgasse',
			filename: '257_sackgasse.svg',
			name: { de: 'Sackgasse' },
			tags: ['square', 'blue'],
			frequency: 'high',
			location: ['city'],
		},
		{ id: '267_einfahrt-verbot', filename: '267_einfahrt-verbot.svg' },
		{
			id: '270.1_umweltzone-beginn',
			filename: '270.1_umweltzone-beginn.svg',
		},
		{ id: '270.2_umweltzone-ende', filename: '270.2_umweltzone-ende.svg' },
		{ id: '272_wendens-verbot', filename: '272_wendens-verbot.svg' },
		{
			id: '274-100_hoechstgeschwindigkeit-100',
			filename: '274-100_hoechstgeschwindigkeit-100.svg',
		},
		{
			id: '274-110_hoechstgeschwindigkeit-110',
			filename: '274-110_hoechstgeschwindigkeit-110.svg',
		},
		{
			id: '274-120_hoechstgeschwindigkeit-120',
			filename: '274-120_hoechstgeschwindigkeit-120.svg',
		},
		{
			id: '274-130_hoechstgeschwindigkeit-130',
			filename: '274-130_hoechstgeschwindigkeit-130.svg',
		},
		{
			id: '274-30_hoechstgeschwindigkeit-30',
			filename: '274-30_hoechstgeschwindigkeit-30.svg',
		},
		{
			id: '274-40_hoechstgeschwindigkeit-40',
			filename: '274-40_hoechstgeschwindigkeit-40.svg',
		},
		{
			id: '274-50_hoechstgeschwindigkeit-50',
			filename: '274-50_hoechstgeschwindigkeit-50.svg',
		},
		{
			id: '274-60_hoechstgeschwindigkeit-60',
			filename: '274-60_hoechstgeschwindigkeit-60.svg',
		},
		{
			id: '274-70_hoechstgeschwindigkeit-70',
			filename: '274-70_hoechstgeschwindigkeit-70.svg',
		},
		{
			id: '274-80_hoechstgeschwindigkeit-80',
			filename: '274-80_hoechstgeschwindigkeit-80.svg',
		},
		{
			id: '274-90_hoechstgeschwindigkeit-90',
			filename: '274-90_hoechstgeschwindigkeit-90.svg',
		},
		{ id: '274.1_zone-30-beginn', filename: '274.1_zone-30-beginn.svg' },
		{ id: '274.2_zone-30-ende', filename: '274.2_zone-30-ende.svg' },
		{
			id: '276_ueberholverbot-kraftfahrzeuge',
			filename: '276_ueberholverbot-kraftfahrzeuge.svg',
		},
		{
			id: '277_ueberholverbot-kraftfahrzeuge-schwer',
			filename: '277_ueberholverbot-kraftfahrzeuge-schwer.svg',
		},
		{
			id: '280_ueberholverbot-kraftfahrzeuge-ende',
			filename: '280_ueberholverbot-kraftfahrzeuge-ende.svg',
		},
		{
			id: '281_ueberholverbot-kraftfahrzeuge-schwer',
			filename: '281_ueberholverbot-kraftfahrzeuge-schwer.svg',
		},
		{
			id: '282_ende-saemtlicher-verbote',
			filename: '282_ende-saemtlicher-verbote.svg',
		},
		{
			id: '283_haltverbot-absolutes',
			filename: '283_haltverbot-absolutes.svg',
		},
		{
			id: '290.1_zone-halteverbot-beginn',
			filename: '290.1_zone-halteverbot-beginn.svg',
		},
		{
			id: '290.2_zone-halteverbot-ende',
			filename: '290.2_zone-halteverbot-ende.svg',
		},
		{ id: '306_vorfahrtstrasse', filename: '306_vorfahrtstrasse.svg' },
		{
			id: '308_vorrang-vor-dem-gegenverkehr',
			filename: '308_vorrang-vor-dem-gegenverkehr.svg',
		},
		{
			id: '314-50_parkhaus-parkgarage',
			filename: '314-50_parkhaus-parkgarage.svg',
		},
		{
			id: '314.1_zone-parkraum-beginn',
			filename: '314.1_zone-parkraum-beginn.svg',
		},
		{ id: '314_parken', filename: '314_parken.svg' },
		{
			id: '314.2_zone-parkraum-ende',
			filename: '314.2_zone-parkraum-ende.svg',
		},
		{
			id: '325.1_verkehrsberuhigtes-bereich-beginn',
			filename: '325.1_verkehrsberuhigtes-bereich-beginn.svg',
		},
		{
			id: '325.2_verkehrsberuhigtes-bereichs-ende',
			filename: '325.2_verkehrsberuhigtes-bereichs-ende.svg',
		},
		{ id: '327_tunnel', filename: '327_tunnel.svg' },
		{ id: '330.1_autobahn', filename: '330.1_autobahn.svg' },
		{ id: '330.2_autobahn-ende', filename: '330.2_autobahn-ende.svg' },
		{
			id: '331.1_kraftfahrstrasse-beginn',
			filename: '331.1_kraftfahrstrasse-beginn.svg',
		},
		{
			id: '331.2_kraftfahrstrasse-ende',
			filename: '331.2_kraftfahrstrasse-ende.svg',
		},
		{
			id: '333_ausfahrt-autobahn',
			filename: '333_ausfahrt-autobahn.svg',
			name: { de: 'Ausfahrt von der Autobahn' },
			tags: ['rectangle', 'blue', 'landscape'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '333.1_ausfahrt-nicht-autobahn',
			filename: '333.1_ausfahrt-nicht-autobahn.svg',
			name: { de: 'Ausfahrt von anderen Straßen außerhalb der Autobahn' },
			tags: ['rectangle', 'yellow', 'landscape'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '350-10_fussgaengerueberweg-rechts',
			filename: '350-10_fussgaengerueberweg-rechts.svg',
			name: { de: 'Fußgängerüberweg, Aufstellung rechts' },
			tags: ['square', 'blue', 'right', 'pedestrian'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '350-20_fussgaengerueberweg-links',
			filename: '350-20_fussgaengerueberweg-links.svg',
			name: { de: 'Fußgängerüberweg, Aufstellung links' },
			tags: ['square', 'blue', 'left', 'pedestrian'],
			frequency: 'high',
			location: ['city'],
		},
		{
			id: '454-10_umleitung-links',
			filename: '454-10_umleitung-links.svg',
			name: { de: 'Umleitungs­wegweiser, linksweisend' },
			tags: ['rectangle', 'yellow', 'left'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '454-20_umleitung-rechts',
			filename: '454-20_umleitung-rechts.svg',
			name: { de: 'Umleitungs­wegweiser, rechtsweisend' },
			tags: ['rectangle', 'yellow', 'right'],
			frequency: 'low',
			location: ['city', 'highway'],
		},
		{
			id: '720_gruenpfeil',
			filename: '720_gruenpfeil.svg',
			name: { de: 'Grünpfeilschild' },
			tags: ['square', 'black'],
			frequency: 'low',
			location: ['city'],
		},
	],
};
export default config;
