name: Deploy and Release Apps via FTP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        required: true
        default: 'verbose'
        options:
          - minimal
          - standard
          - verbose

  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Build and deploy app

    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Install packages
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Compile source
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: Deploy code
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './dist/*'
          remote: '/home/www/de.absolutholz.arcade/travelbingo/'
          host: ${{secrets.WEBGO_SFTP_HOST}}
          user: ${{secrets.WEBGO_SFTP_USERNAME}}
          password: ${{secrets.WEBGO_SFTP_PASSWORD}}
