name: Deploy and Release Apps via FTP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        required: true
        default: 'verbose'
        options:
          - minimal
          - standard
          - verbose

  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Build and deploy app

    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Install packages
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Compile source
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.WEBGO_SFTP_USERNAME }}@${{ secrets.SSH_HOST }}:/home/www/de.absolutholz.arcade/travelbingo/
