name: Deploy and Release Apps via FTP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        options:
          - minimal
          - standard
          - verbose'
        required: true
        default: 'verbose'

  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy app

    runs-on: ubuntu-latest
    env:
      working-directory: .
      VITE_PUBNUB_PUBLISH_KEY: pub-c-420655f2-9ceb-475d-ae5c-44007d085fa1
      VITE_PUBNUB_SUBSCRIBE_KEY: sub-c-7061a764-0f86-4b92-92f2-da4126e9c981
      VITE_APP_URL: https://arcade.absolutholz.com/travelbingo

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Install packages
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Compile source
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: Upload to host via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.WEBGO_SFTP_HOST }}
          port: ${{ secrets.WEBGO_SFTP_PORT }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          password: ${{ secrets.WEBGO_SFTP_PASSWORD }}
          protocol: ftp
          local-dir: ./dist/
          server-dir: /home/www/de.absolutholz.arcade/travel-bingo
          log-level: ${{ github.event.inputs.logLevel }}
